/** Real S11 React UI, coverage/listings hooks, validators and request client.
 * Apple SDK, transport and location lookup are controlled boundaries.
 * These browser fixtures do not replace real PostGIS/Apple/device acceptance. */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

const web = path.resolve(__dirname, '../apps/web');
const req = createRequire(path.join(web, 'package.json'));
const esbuild = req(req.resolve('esbuild', { paths: [req.resolve('tsx')] }));
const { chromium, expect } = req('@playwright/test');

async function main() {
  const mocks: Record<string, string> = {
    'next/link': `import React from 'react';export default function Link({href,children,...props}){return <a href={href} {...props}>{children}</a>;}`,
    'next/image': `import React from 'react';export default function Image({fill,sizes,...props}){return <img {...props}/>;}`,
    'next/dynamic': `import React,{lazy,Suspense} from 'react';export default function dynamic(load){const C=lazy(load);return p=><Suspense fallback={null}><C {...p}/></Suspense>;}`,
    'next-themes': `export const useTheme=()=>({resolvedTheme:window.f.theme});`,
    '@/hooks/use-mapkit': `export const useMapKit=()=>({isReady:!window.f.loading,isAvailable:window.f.available,mapkit:window.f.sdk,retry:()=>{window.f.available=true;window.f.redraw();},retryWaitSeconds:0});`,
    '@/components/layout/session-data-provider': `import {useState} from 'react';export function useSessionUI(key,initial){const [ui,setUI]=useState(()=>window.f.ui[key]??initial);return [ui,v=>{window.f.ui[key]=v;setUI(v);}];}`,
    '@/hooks/useGeolocation': `export const useGeolocation=()=>({state:{status:'idle'},request:()=>{window.f.gps++;}});`,
    '@/hooks/use-reverse-geocode': `export function useReverseGeocode(p){if(p)window.f.geocode++;return {name:null};}`,
    '@/components/home/change-location-sheet': `import React from 'react';export function ChangeLocationSheet({open,onClose}){return open?<div role="dialog"><button onClick={()=>{window.dispatchEvent(new CustomEvent('vicino_location_updated',{detail:{lat:19.09,lng:-98.19,radius:10000}}));onClose();}}>Aplicar zona de prueba</button></div>:null;}`,
    '@/lib/geo/location-search': `export const clasificarResultado=()=> 'ok';export const searchLocations=async()=>({results:[]});export const resolveLocationCoordinates=async s=>s;`,
    '@/lib/geo/cobertura': `export const useReglaCobertura=()=>({});`,
    '@/lib/geo/apple-geocoder': `export const reverseGeocodeWithApple=async()=>({name:'Zona sintética',fullName:'Zona sintética, México'});`,
  };
  mocks['./change-location-sheet'] = mocks['@/components/home/change-location-sheet'];
  const bundle = await esbuild.build({ stdin: { resolveDir: web, loader: 'tsx', contents: `
    import React,{useState} from 'react';import {createRoot} from 'react-dom/client';
    import {MapExplorer} from './app/(marketplace)/mapa/map-explorer';
    import {mapQuerySchema,MAP_AREA} from '@vicino/shared';import LocationPicker from './components/map/location-picker';
    const f=window.f;
    class Coordinate{constructor(latitude,longitude){Object.assign(this,{latitude,longitude});}}
    class Span{constructor(latitudeDelta,longitudeDelta){Object.assign(this,{latitudeDelta,longitudeDelta});}}
    class Region{constructor(center,span){Object.assign(this,{center,span});}}
    class Marker{constructor(coordinate,opts){this.coordinate=coordinate;this.opts=opts;this.events={};}addEventListener(t,cb){this.events[t]=cb;}}
    class Map{static ColorSchemes={Dark:'dark',Light:'light'};constructor(node,opts){this.node=node;this.region=opts.region;this.events={};this.markers=[];this.recenters=0;f.maps.push(this);node.dataset.testid='sdk-map';node.style.background='repeating-linear-gradient(33deg,transparent 0 80px,#d0ddce 82px 86px,transparent 88px 160px),#ecede3';}
      addEventListener(t,cb){this.events[t]=cb;}setRegionAnimated(r){this.region=r;this.recenters++;this.events['region-change-end']?.({});}
      addAnnotation(m){this.markers.push(m);const b=document.createElement('button');b.textContent=m.opts?.glyphText??'Punto';b.setAttribute('aria-label',m.opts?.title??'Punto');b.dataset.marker='true';Object.assign(b.style,{position:'absolute',left:'52%',top:'48%',borderRadius:'50%',background:m.opts?.color??'#1F5A4E',color:'white',width:'44px',height:'44px'});b.onclick=()=>m.events.select?.();m.button=b;this.node.append(b);}
      removeAnnotation(m){m.button?.remove();this.markers=this.markers.filter(x=>x!==m);}convertPointOnPageToCoordinate(){return f.point;}addOverlay(o){f.overlays.push(o);}removeOverlay(){}destroy(){this.destroyed=true;this.node.replaceChildren();}}
    f.sdk={Map,Coordinate,CoordinateSpan:Span,CoordinateRegion:Region,MarkerAnnotation:Marker,CircleOverlay:class{constructor(c,r){this.radius=r;}},Style:class{},FeatureVisibility:{Adaptive:'a',Hidden:'h'}};
    f.map=()=>f.maps.filter(m=>!m.destroyed).at(-1);
    f.camera=(lat=19.05,lng=-98.22,span=.12)=>{const m=f.map();m.region=new Region(new Coordinate(lat,lng),new Span(span,span));m.events['region-change-end']?.({});};
    const uid=n=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0');
    f.result=r=>{const second=!!r.query.cursor,empty=r.query.q==='sin resultados'||!!f.remoteEmpty;return {query_key:'a'.repeat(32),revision:f.revision??'b'.repeat(32),projection_version:1,as_of:'2026-09-30',
      features:empty?[]:[{id:'cell:1:-9823:1904',public_lat:19.04,public_lng:-98.23,count:35,seller_count:3,bounds:{west:-98.23,south:19.04,east:-98.23,north:19.04}}],
      total:empty?0:35,seller_total:empty?0:3,list_total:r.action==='listings'&&!empty?35:0,list_seller_total:r.action==='listings'&&!empty?3:0,
      listings:r.action==='listings'&&!empty?Array.from({length:second?5:30},(_,i)=>({id:uid(i+(second?31:1)),titulo:'Publicación '+(i+(second?31:1)),slug:'publicacion-'+i,categoria:'comida',precio:i<2?null:80+i,modo_precio:i===0?'cotizacion':i===1?'reservacion':'precio',tipo:'producto',imagen_principal:null,creador_id:uid(99),vendedor_nombre:'Negocio de prueba',cell_id:r.query.cell_id,seller_listing_count:35,created_at:'2026-09-30T12:00:00Z'})):[],
      next_cursor:r.action==='listings'&&!empty&&!second?{key:'a'.repeat(32),id:uid(30),created_at:'2026-09-30T12:00:00Z'}:null,
      cells:r.action==='cells'&&!empty?[{x:-9823,y:1904,count:35,seller_count:3}]:[],next_cell_cursor:null,complete:r.action==='cells'||empty};};
    window.fetch=async(url,opts)=>{const r=JSON.parse(opts.body);const item={url,r,aborted:false};f.requests.push(item);opts.signal.addEventListener('abort',()=>item.aborted=true);await new Promise(resolve=>setTimeout(resolve,r.query.q==='antigua'?1200:20));return new Response(JSON.stringify(f.fail?{error:'Fallo sintético recuperable'}:f.result(r)),{status:f.fail?503:200,headers:{'Content-Type':'application/json'}});};
    const initial=mapQuerySchema.parse({bounds:f.national?MAP_AREA:{west:-98.32,south:18.94,east:-98.10,north:19.15}});
    function Harness(){const [tick,setTick]=useState(0);f.redraw=()=>setTick(n=>n+1);
      if(location.pathname==='/picker')return <LocationPicker initialLat={19.04} initialLng={-98.21} initialRadius={5} onRadiusChange={n=>f.radiusWrites.push(n)} showRadiusControl={false} showRadiusPreview={f.circle} onChange={p=>f.locationWrites.push(p)}/>;
      return f.mounted?<MapExplorer key={f.session} viewerScope={f.viewer} initialQuery={initial} initialCenter={f.national?null:{lat:19.04,lng:-98.21}}/>:null;
    }
    createRoot(document.getElementById('root')).render(<Harness/>);
  ` }, bundle: true, write: false, platform: 'browser', format: 'iife', jsx: 'automatic', tsconfig: path.join(web, 'tsconfig.json'), define: { 'process.env.NODE_ENV': '"production"', 'process.env': '{}' }, plugins: [{ name: 'boundaries', setup(b: any) { b.onResolve({ filter: /.*/ }, (a: any) => Object.hasOwn(mocks, a.path) ? { path: a.path, namespace: 'mock' } : undefined); b.onLoad({ filter: /.*/, namespace: 'mock' }, (a: any) => ({ contents: mocks[a.path], loader: 'tsx', resolveDir: web })); } }] });
  const postcss = createRequire(req.resolve('@tailwindcss/postcss'))('postcss');
  const cssFile = path.join(web, 'app/globals.css');
  const { css } = await postcss([req('@tailwindcss/postcss')({ base: web })]).process(readFileSync(cssFile, 'utf8'), { from: cssFile });
  const out = path.join(web, 'test-results/s11'); mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ channel: 'chrome', headless: true }); let passed = 0;
  try {
    for (const viewport of [{ width: 390, height: 844 }, { width: 820, height: 1180 }, { width: 1280, height: 900 }]) {
      const context = await browser.newContext({ viewport }); const page = await context.newPage(); page.setDefaultTimeout(8000); const errors: string[] = [];
      page.on('pageerror', (error: Error) => errors.push(error.message));
      await page.route('**/*', async (route: any) => route.request().isNavigationRequest() ? route.fulfill({ contentType: 'text/html', body: '<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><body><div id="root"></div></body></html>' }) : route.abort());
      const pass = (name: string) => { passed++; console.log('PASS ' + viewport.width + ' ' + name); };
      async function mount(route = '/mapa', extra = {}) { await page.goto('https://s11.invalid' + route); await page.evaluate(extra => { (window as any).f = { maps: [], overlays: [], requests: [], gps: 0, geocode: 0, ui: {}, session: 'a', viewer: 'guest', theme: 'light', available: true, mounted: true, radiusWrites: [], locationWrites: [], ...extra }; }, extra); await page.addStyleTag({ content: css }); await page.addScriptTag({ content: bundle.outputFiles[0].text }); }
      await mount(); try { await expect(page.getByText('35 publicaciones · 3 vendedores', { exact: true })).toBeVisible(); } catch (error) { console.error(JSON.stringify({ errors, fixture: await page.evaluate(() => ({ text: document.body.innerText, requests: (window as any).f.requests })) }, null, 2)); throw error; } await expect.poll(() => page.evaluate(() => (window as any).f.requests.some((r: any) => r.r.action === 'cells'))).toBe(true);
      await expect(page.locator('article')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Filtros', exact: true })).toHaveCount(1); assert.equal(await page.evaluate(() => (window as any).f.gps), 0); assert.equal(await page.evaluate(() => (window as any).f.geocode), 0); assert.equal(await page.evaluate(() => (window as any).f.maps.length), 1); pass('no permanent products or duplicate filters; one SDK; no GPS/geocode');
      const initialCalls = await page.evaluate(() => (window as any).f.requests.length); await page.evaluate(() => { const f = (window as any).f; f.camera(19.05, -98.22, .15); f.camera(19.05, -98.22, .07); }); await page.waitForTimeout(550); assert.equal(await page.evaluate(() => (window as any).f.requests.length), initialCalls); assert.equal(await page.evaluate(() => (window as any).f.maps.length), 1); pass('pan and zoom inside loaded coverage make zero new API calls');
      await page.locator('[data-marker]').first().click(); await expect(page.getByRole('dialog')).toBeVisible(); await expect(page.locator('article')).toHaveCount(30); await expect(page.getByRole('dialog')).toContainText('35 publicaciones · 3 vendedores'); await page.getByRole('button', { name: 'Ver más publicaciones', exact: true }).click(); await expect(page.locator('article')).toHaveCount(35);
      const detailCalls = await page.evaluate(() => (window as any).f.requests.filter((r: any) => r.r.action === 'listings').length); await page.evaluate(() => (window as any).f.camera(19.05, -98.22, .05)); await page.waitForTimeout(450); assert.equal(await page.evaluate(() => (window as any).f.requests.filter((r: any) => r.r.action === 'listings').length), detailCalls); pass('pin drawer loads 30, cursor appends 5, group remains frozen on camera');
      await page.getByRole('button', { name: 'Cerrar publicaciones', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.locator('article')).toHaveCount(0); assert.equal(await page.getByRole('region', { name: 'Explorar publicaciones en el mapa' }).evaluate(el => document.activeElement === el), true); pass('X closes and returns focus without opening the keyboard');
      await page.getByText('Puntos del mapa', { exact: true }).click(); await page.getByRole('button', { name: 'Punto 1 · 35 publicaciones', exact: true }).click(); await expect(page.getByRole('dialog')).toBeVisible(); await expect(page.locator('article')).toHaveCount(30); await expect(page.getByText('Cotización', { exact: true })).toBeVisible(); await expect(page.getByText('Reservación', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Ver más publicaciones', exact: true }).click(); await expect(page.locator('article')).toHaveCount(35); pass('reopening after 35 resets page and can load more; actual price modes'); await page.evaluate(() => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))); await expect(page.getByRole('dialog')).toHaveCount(0); assert.equal(await page.getByRole('button', { name: 'Punto 1 · 35 publicaciones', exact: true }).evaluate(el => document.activeElement === el), true); pass('accessible point and synthetic native Back/Escape return focus');
      await page.getByRole('button', { name: 'Filtros', exact: true }).click(); const beforeDraft = await page.evaluate(() => (window as any).f.requests.length); await page.getByRole('button', { name: 'Productos', exact: true }).click(); await page.waitForTimeout(420); assert.equal(await page.evaluate(() => (window as any).f.requests.length), beforeDraft); await page.getByRole('button', { name: 'Aplicar', exact: true }).click(); await expect.poll(() => page.evaluate(() => (window as any).f.requests.at(-1).r.query.tipo)).toBe('producto'); assert.equal(new URL(page.url()).searchParams.get('tipo'), 'producto'); pass('filter draft does not query; apply persists URL');
      await page.evaluate(() => { const f = (window as any).f; f.camera(19.05, -98.22, 2); }); await expect.poll(() => page.evaluate(() => (window as any).f.requests.at(-1).r.coverage_center)).toBe(null); await page.evaluate(() => (window as any).f.camera(19.05, -98.22, .1)); await expect.poll(() => page.evaluate(() => (window as any).f.requests.at(-1).r.coverage_center?.lat)).toBe(19.05); assert.equal(await page.evaluate(() => (window as any).f.maps.length), 1); pass('regional wide zoom uses complete overview and refines again');
      await page.evaluate(() => { history.pushState(history.state, '', '/mapa?q=desde%20historial&tipo=servicio&price_min=50'); history.pushState(history.state, '', '/mapa?q=otra'); history.back(); }); await expect(page.getByRole('searchbox')).toHaveValue('desde historial'); await expect.poll(() => page.evaluate(() => (window as any).f.requests.at(-1).r.query.tipo)).toBe('servicio'); await expect.poll(() => page.evaluate(() => (window as any).f.requests.at(-1).r.query.price_min)).toBe(50); pass('Back restores URL filters instead of stale mounted state');
      await page.evaluate(() => { (window as any).f.theme = 'dark'; document.documentElement.classList.add('dark'); (window as any).f.redraw(); }); await expect.poll(() => page.evaluate(() => (window as any).f.map().colorScheme)).toBe('dark'); await page.emulateMedia({ reducedMotion: 'reduce' }); await page.locator('[data-marker]').first().click(); await expect(page.getByRole('dialog')).toBeVisible(); await page.screenshot({ path: path.join(out, 'map-drawer-dark-' + viewport.width + '.png'), fullPage: false }); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); pass('dark and reduced-motion drawer close');
      await page.emulateMedia({ reducedMotion: 'no-preference' }); await page.locator('[data-marker]').first().click(); await expect(page.getByRole('dialog')).toBeVisible(); const handle = page.getByRole('button', { name: 'Cerrar o deslizar hacia abajo las publicaciones', exact: true }); const box = await handle.boundingBox(); assert.ok(box); await page.mouse.move(box.x + box.width / 2, box.y + 12); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2, box.y + 175, { steps: 12 }); await page.mouse.up(); await expect(page.getByRole('dialog')).toHaveCount(0); pass('dragging only the sheet handle dismisses downward');
      await page.evaluate(() => window.dispatchEvent(new CustomEvent('vicino_location_updated', { detail: null }))); await expect(page.getByRole('button', { name: 'Activar ubicación', exact: true })).toBeVisible(); await expect.poll(() => page.evaluate(() => (window as any).f.requests.at(-1).r.coverage_center)).toBe(null); assert.equal(await page.evaluate(() => (window as any).f.map().region.span.longitudeDelta), 32); pass('clearing location returns to Mexico without invented preference');
      await page.locator('[data-marker]').first().click(); await expect(page.locator('article')).toHaveCount(30); await page.evaluate(() => { const f = (window as any).f; f.remoteEmpty = true; f.revision = 'c'.repeat(32); document.dispatchEvent(new Event('visibilitychange')); }); await expect(page.getByText('Ya no hay publicaciones en este punto', { exact: true })).toBeVisible(); await expect(page.locator('article')).toHaveCount(0); await expect(page.getByRole('dialog')).toBeVisible(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); pass('visible drawer revalidates changed revision and removes expired cards');
      await mount('/mapa', { available: false }); await expect(page.getByRole('link', { name: 'Ver publicaciones de esta zona', exact: true })).toBeVisible(); await expect(page.locator('article')).toHaveCount(0); pass('SDK failure preserves accessible catalog link');
      await mount('/picker', { circle: false }); await expect(page.locator('[data-testid="sdk-map"]')).toBeVisible(); await expect(page.getByRole('slider')).toHaveCount(0); assert.equal(await page.evaluate(() => (window as any).f.overlays.length), 0); await page.evaluate(() => { const f = (window as any).f; f.point = { latitude: 19.06, longitude: -98.22 }; f.map().events['single-tap']({ pointOnPage: { x: 1, y: 1 } }); }); await expect.poll(() => page.evaluate(() => (window as any).f.locationWrites.at(-1)?.lat)).toBe(19.06); assert.deepEqual(await page.evaluate(() => (window as any).f.radiusWrites), []); assert.equal(await page.evaluate(() => (window as any).f.map().recenters), 0); pass('publication preview hides circle/control, preserves pin and saved radius contract');
      await mount('/picker'); await expect.poll(() => page.evaluate(() => (window as any).f.overlays.at(-1)?.radius)).toBe(5000); pass('other pickers retain their default radius preview');
      assert.deepEqual(errors, []); await context.close();
    }
  } finally { await browser.close(); }
  console.log('S11 map browser: ' + passed + '/' + passed + ' PASS; controlled SDK and transport');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
